services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/kanban_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: